MyDefenceSistem/Models/DefinceWeapon.cs
using System.ComponentModel.DataAnnotations;

namespace MyDefenceSistem.Models
{
    public class DefinceWeapon
    {
        public int Id { get; set; }
        [Display(Name = "סוג נשק הגנתי")]
        public string Name { get; set; }
        [Display(Name = "כמות")]

        public int quantity { get; set; }
    }
}

MyDefenceSistem/Models/Enums.cs
namespace MyDefenceSistem.Models
{
    public class Enums
    {
        public enum ThreatStatus
        {
            Active,
            NonActive,
            Done
        }
    }
}

MyDefenceSistem/Models/ErrorViewModel.cs
namespace MyDefenceSistem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyDefenceSistem/Models/Origin.cs
namespace MyDefenceSistem.Models
{
    public class Origin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Distance { get; set; }
    }
}

MyDefenceSistem/Models/Threat.cs
using System.ComponentModel.DataAnnotations;
using static MyDefenceSistem.Models.Enums;

namespace MyDefenceSistem.Models
{
    public class Threat
    {
        [Key]
        public int ThreatId { get; set; }

        [Required]
        [Display(Name = "מקום שיגור")]
        public int OriginId { get; set; }

        public Origin? Origin { get; set; }


        [Display(Name = "זמן שיגור")]
        public DateTime? LaunchTime { get; set; }


        [Display(Name = "סוג נשק")]
        public int WeaponId { get; set; }

        public Weapon? Weapon { get; set; }


        [Display(Name = "כמות טילים")]
        public int MissleQuantity { get; set; }


        [Display(Name = "כמות טילים שיורטו")]
        public int? hitted { get; set; }

        public int ? TimeToHit { get; set; }

        [Display(Name = "מצב האיום")]
        public ThreatStatus Status { get; set; }
    }
}

MyDefenceSistem/Models/Weapon.cs
using static MyDefenceSistem.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace MyDefenceSistem.Models
{
    public class Weapon
    {
        [Key]
        public int WeaponId { get; set; }
        [Required]
        public string Type { get; set; }
        public int Speed { get; set; }
        public int definceWeaponId { get; set; }
        public DefinceWeapon definceWeapon { get; set; }
    }
}

MyDefenceSistem/Controllers/DefinceWeaponsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyDefenceSistem.BL;
using MyDefenceSistem.Data;
using MyDefenceSistem.Models;

namespace MyDefenceSistem.Controllers
{
    public class DefinceWeaponsController : Controller
    {
        private readonly IDefenceWeaponService _defenceWeaponService;

        public DefinceWeaponsController(IDefenceWeaponService defenceWeaponService)
        {
            _defenceWeaponService = defenceWeaponService;
        }

        // GET: DefinceWeapons
        public async Task<IActionResult> Index()
        {
            return View(await _defenceWeaponService.GetTable());
        }

        [HttpPost]
        public async Task<IActionResult> UpdateQuantity(int id, int quantity)
        {
            var sucsses = await _defenceWeaponService.UpdateQuantity(id, quantity);
            if (!sucsses) return BadRequest();
            return RedirectToAction(nameof(Index));
        }
        

    }
}

MyDefenceSistem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyDefenceSistem.Models;
using System.Diagnostics;

namespace MyDefenceSistem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyDefenceSistem/Controllers/ThreatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyDefenceSistem.Data;
using MyDefenceSistem.Models;
using MyDefenceSistem.Services;
using static MyDefenceSistem.Models.Enums;

namespace MyDefenceSistem.Controllers
{
    public class ThreatsController : Controller
    {
        private readonly MyDefenceSistemContext _context;
        private readonly ThreatsService _treatService;

        public ThreatsController(MyDefenceSistemContext context, ThreatsService threatsService)
        {
            _context = context;
            _treatService = threatsService;
        }

        // GET: Threats
        public async Task<IActionResult> Index()
        {
            var myDefenceSistemContext = _context.Threat.Include(t => t.Origin).Include(t => t.Weapon).Where(t => t.Status == ThreatStatus.NonActive);
            return View(await myDefenceSistemContext.ToListAsync());
        }

        // GET: Threats/Create
        public IActionResult Create()
        {
            ViewData["OriginId"] = new SelectList(_context.Origins, "Id", "Name");
            ViewData["WeaponId"] = new SelectList(_context.Weapons, "WeaponId", "Type");
            return View();
        }

        // POST: Threats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OriginId,WeaponId,MissleQuantity,Status")] Threat threat)
        {

            if (ModelState.IsValid)
            {
                threat.hitted = 0;
                _context.Add(threat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OriginId"] = new SelectList(_context.Origins, "Id", "Id", threat.OriginId);
            ViewData["WeaponId"] = new SelectList(_context.Weapons, "WeaponId", "Type", threat.WeaponId);
            return View(threat);
        }

        // GET: Threats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var threat = await _context.Threat.FindAsync(id);
            if (threat != null)
            {
                _context.Threat.Remove(threat);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Launch(int id)
        {
            if (id == 0 || id == null) 
                return NotFound();
            var threat = _context.Threat.Include(t => t.Weapon).Include(t => t.Origin).FirstOrDefault(t => t.ThreatId == id);
            if (threat == null || threat.Status == ThreatStatus.Done || threat.Status == ThreatStatus.Active)
            {
                return RedirectToAction(nameof(Index), new { Error = "Attack not found" });
            }
            await _treatService.Launch(threat);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Defence()
        {
            return View();
        }
        private bool ThreatExists(int id)
        {
            return _context.Threat.Any(e => e.ThreatId == id);
        }
    }
}

MyDefenceSistem/Views/DefinceWeapons/Index.cshtml
@model IEnumerable<MyDefenceSistem.Models.DefinceWeapon>

@{
    ViewData["Title"] = "Index";
}

<h1>מערכות הגנה</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <form asp-action="UpdateQuantity" method="post">
                        <input type="hidden" name="Id" value="@item.Id" />
                        <input type="number" name="Quantity" value="@item.quantity" class="form-control" />
                        <button type="submit" class="btn btn-primary">עדכן כמות</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

MyDefenceSistem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">צבא ההגנה לישראל</h1>
</div>

MyDefenceSistem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyDefenceSistem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyDefenceSistem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">מערכת ההגנה</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DefinceWeapons" asp-action="Index">מחסן הנשק</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Threats" asp-action="Index">ניהול איומים</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Threats" asp-action="Defence">ניהול הגנה</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyDefenceSistem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyDefenceSistem/Views/Threats/Create.cshtml
@model MyDefenceSistem.Models.Threat

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Threat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OriginId" class="control-label"></label>
                <select asp-for="OriginId" class ="form-control" asp-items="ViewBag.OriginId"></select>
            </div>
            <div class="form-group">
                <label asp-for="WeaponId" class="control-label"></label>
                <select asp-for="WeaponId" class ="form-control" asp-items="ViewBag.WeaponId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MissleQuantity" class="control-label"></label>
                <input asp-for="MissleQuantity" class="form-control" />
                <span asp-validation-for="MissleQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Status" value="NonActive" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyDefenceSistem/Views/Threats/Defence.cshtml
@{
    ViewData["Title"] = "Defence";
}

<h2>חדר מצב</h2>

<div id="specialMessages" class="alert"></div>

<div id="tableContainer">
    <h3>איומים פעילים</h3>
    <table id="queue1Table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Threat ID</th>
                <th>מקום שיגור</th>
                <th>זמן שיגור</th>
                <th>סוג נשק</th>
                <th>כמות טילים</th>
                <th>זמן לפגיעה</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <button id="sendmissle" class="btn btn-primary">שגר</button>

    <h3>איומים שיורטו</h3>
    <table id="queue2Table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Threat ID</th>
                <th>מקום שיגור</th>
                <th>זמן שיגור</th>
                <th>סוג נשק</th>
                <th>כמות טילים שיורטו</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

    <h3>איומים שפגעו</h3>
    <table id="queue3Table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Threat ID</th>
                <th>מקום שיגור</th>
                <th>זמן שיגור</th>
                <th>סוג נשק</th>
                <th>כמות טילים</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

@section scripts {
    <script src="~/lib/signalr/signalr.min.js"></script>
    <script type="text/javascript">
        const connection = new signalR.HubConnectionBuilder().withUrl("/threat_hub").build();

        // קבלת הודעות מה-Hub
        connection.on("BE_ReciveThreatsQueue", function (queue1) {
            console.log(queue1);
            populateTable(queue1, "#queue1Table");
        });

        connection.on("ReceiveQueue", function (queue2) {
            populateTable3(queue2, "#queue2Table");
        });

        connection.on("ReceiveQueue", function (queue3) {
            populateTable2(queue3, "#queue3Table");
        });
        connection.on("ReciveUpdate", function (id, time) {
            updatetime(id, time)
        })

        connection.on("SpecialMessage", function (message) {
            displaySpecialMessage(message);
        });

        connection.start()
            .then(function () {
                connection.invoke("SendInitialRequest")
            }).catch(function (err) {
                return console.error(err.toString());
            });

        document.getElementById("sendmissle").addEventListener("click", function () {
            connection.invoke("sendmissle").catch(function (err) {
                return console.error(err.toString());
            });
        });

        function populateTable(queue, tableId) {
            const tableBody = document.querySelector(tableId + " tbody");
            tableBody.innerHTML = ""; // clear existing rows

            queue.forEach(function (threat) {
                const row = document.createElement("tr");

                row.innerHTML = `
                                    <td>${threat.threatId}</td>
                                    <td>${threat.origin ? threat.origin.name : ''}</td>
                                    <td>${threat.launchTime ? new Date(threat.launchTime).toLocaleString() : ''}</td>
                                    <td>${threat.weapon ? threat.weapon.type : ''}</td>
                                    <td>${threat.missleQuantity}</td>
                                    <td>לא מוגדר</td>
                                `;

                tableBody.appendChild(row);
            });
        }
        function populateTable2(queue, tableId) {
            const tableBody = document.querySelector(tableId + " tbody");
            tableBody.innerHTML = ""; // clear existing rows

            queue.forEach(function (threat) {
                if (threat.missleQuantity === 0) {
                    return;
                }
                const row = document.createElement("tr");

                row.innerHTML = `
                                            <td>${threat.threatId}</td>
                                            <td>${threat.origin ? threat.origin.name : ''}</td>
                                            <td>${threat.launchTime ? new Date(threat.launchTime).toLocaleString() : ''}</td>
                                            <td>${threat.weapon ? threat.weapon.type : ''}</td>
                                            <td>${threat.missleQuantity}</td>
                                        `;

                tableBody.appendChild(row);
            });
        }
        function populateTable3(queue, tableId) {
            const tableBody = document.querySelector(tableId + " tbody");
            tableBody.innerHTML = ""; // clear existing rows

            queue.forEach(function (threat) {
                if (threat.hitted === 0) {
                    return;
                }
                const row = document.createElement("tr");

                row.innerHTML = `
                            <td>${threat.threatId}</td>
                            <td>${threat.origin ? threat.origin.name : ''}</td>
                            <td>${threat.launchTime ? new Date(threat.launchTime).toLocaleString() : ''}</td>
                            <td>${threat.weapon ? threat.weapon.type : ''}</td>
                            <td>${threat.hitted}</td>
                                                `;

                tableBody.appendChild(row);
            });
        }
        function displaySpecialMessage(message) {
            const specialMessagesDiv = document.getElementById("specialMessages");
            specialMessagesDiv.innerHTML = message;
            specialMessagesDiv.classList.add("alert-success");
            setTimeout(() => {
                specialMessagesDiv.innerHTML = "";
                specialMessagesDiv.classList.remove("alert-success");
            }, 5000);
        }
        function updatetime(id, time) {
            const tableBody = document.querySelector("#queue1Table tbody");

            // Find the row with the matching threatId
            const row = Array.from(tableBody.querySelectorAll("tr")).find(tr => {
                return tr.querySelector("td").innerText === id.toString();
            });

            if (row) {
                const timeCell = row.querySelector("td:nth-child(6)"); // The 6th column for "זמן לפגיעה"

                // Update the time cell with the remaining time
                if (time <= 0) {
                    timeCell.innerText = "פוגע";
                } else {
                    timeCell.innerText = time;
                }
            }
        }
    </script>
    <style>
        #tableContainer {
            margin-top: 20px;
        }

        .table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }

            .table th, .table td {
                padding: 10px;
                text-align: left;
                border: 1px solid #ddd;
            }

        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #f9f9f9;
        }

        .table-bordered {
            border: 1px solid #ddd;
        }

        #sendmissle {
            margin-top: 15px;
            margin-bottom: 30px;
            display: block;
        }

        .alert {
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid transparent;
            border-radius: 5px;
            color: #ffffff;
            background-color: #4caf50; /* צבע ירוק להודעות */
            font-size: 16px;
            text-align: center;
        }

        .alert-success {
            background-color: #4caf50;
        }
    </style>
}

MyDefenceSistem/Views/Threats/Index.cshtml
@model IEnumerable<MyDefenceSistem.Models.Threat>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weapon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MissleQuantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Origin.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weapon.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MissleQuantity)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.ThreatId">Delete</a>
            </td>
             <td>
                    <form asp-action="Launch" method="post">
                        <input type="hidden" name="id" value="@item.ThreatId" />
                        <button type="submit" class="btn btn-danger">שגר</button>
                    </form>
                </td>
        </tr>
}
    </tbody>
</table>